### ISSUE TITLE
as a user, i should be able to click on a given artwork and view details about that artwork.

### ISSUE THREAD

**Issue by pitter3** [daltobello/stretch-tech#36]
### Acceptance Criteria

- [x] i can see an enlarged view of the artwork and the following details: artist's name, artwork title, date, description, medium, etc.
- [x] i have the option to favorite the artwork by clicking a favorite icon
- [x] i have the option to un-favorite the artwork by clicking a favorite icon again
- [x] i have the option to return to the homepage
- [x] nav bar is visible, all artworks are hidden, and SelectedArtCard is displayed

### Tasks

- [x] store departmentObj in state?
- [x] create onClick attribute (event listener) for the click of an artwork
- [x] get id of clicked artCard. iterate over departmentObj array to find the departmentObj.objectID that matches the id of clicked artCard. 
- [x] create back button functionality that links to home path
